name: Trigger platform deploy

on:
  push:
    branches: [main, test]

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/test'
    uses: couragegang/platform/.github/workflows/deploy-vps.yml@test
    with:
      contour: test
      service_repo: ${{ github.event.repository.name }}
      sha: ${{ github.sha }}
      trigger_repository: ${{ github.repository }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: couragegang/platform/.github/workflows/deploy-vps.yml@main
    with:
      contour: prod
      service_repo: ${{ github.event.repository.name }}
      sha: ${{ github.sha }}
      trigger_repository: ${{ github.repository }}
