name: Trigger platform deploy

on:
  push:
    branches: [main, test]

jobs:
  deploy:
    uses: couragegang/platform/.github/workflows/deploy-vps.yml@${{ github.ref_name }}
    with:
      contour: ${{ github.ref == 'refs/heads/main' && 'prod' || 'test' }}
      service_repo: ${{ github.event.repository.name }}
      sha: ${{ github.sha }}
      trigger_repository: ${{ github.repository }}
